### ISSUE TITLE
Pickaxes problem

### ISSUE THREAD

**Issue by IttoSanzzo** [iwaliner/Urushi-MOD-1.18.2#1]
So, I was kind of doing some things in my modpack, I added Urushi, and I realized that the pickaxes weren't breaking things like they should, it was like having empty hands. Then I did some tests, and it seems that this only happens while Urushi is installed. I've tried in different ways to find out exactly what the problem is, but I couldn't identify it, I just know that removing Urushi and the problem stops, and putting it back, the problem returns... very sad, I was very excited, already which is the best style mod available in 1.18.2..... do you have any idea what it could be...?

**Comment by IttoSanzzo** [comment]
To make things simpler, this is the mod pack in question, in version 6.3, in which I added Urushi, and then I realized the bug while playing..:

https://legacy.curseforge.com/minecraft/modpacks/terrafirmasetsu-reborn

**Comment by IttoSanzzo** [comment]
Nice, seems like its only in the newer version, falling back to the 4.13.0 works for now...

**Comment by iwaliner** [comment]
Thanks for the report.
This bug was fixed on Urushi-1.18.2-4.13.2.

**Comment by IttoSanzzo** [comment]
Thanks for your attention, I really liked the mod, good luck for the future
